#http
version: "3.8"

services:
  app:
    image: ghcr.io/mahn-ke/kiosk-39c3-by-vincent:latest
    restart: on-failure:5
    environment:
      - PORT=3011
    ports:
      - "3011:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3011/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
